sudo: required
services:
        - docker

before_install:
        - docker build -t travisimage -f Dockerfile.dev .

script: 
        - docker run -e CI=true travisimage npm run test

deploy:
        provider: elasticbeanstalk
        region: "us-west-2"
        app: "dockertest"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk_s3_name"
        bucket_path: "dockertest"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"        
