version: '3'
services:
        web: #name of service (any)
                stdin_open: true
                #build: . # . means that we have our docker file inside our working directory
                build:
                        context: . #where all files and folders for this image will be pulled from
                        dockerfile: Dockerfile.dev
                ports:
                        - "3000:3000"
                volumes:
                        - /app/node_modules #do not try to map the folder 
                        - .:/app # map the folder . outside of the container  against the folder /app inside the container
        tests: #second container responsible solely to run tests
                build:
                        context: .
                        dockerfile: Dockerfile.dev
                volumes:
                        - /app/node_modules
                        - .:/app
                command: ["npm", "run", "test"]              
